### ISSUE TITLE
Java Instant parsing problem

### ISSUE THREAD

**Issue by devabdicant** [reinert/JJSchema#60]
Hi!
I am able to create json schemas from a class but when I use parameter type INSTANT or LOCALDATE I get an error. 
Having this
@Attributes(required = false, description = "Task type identificator")
	private LocalDate startingDate;
or this
@Attributes(required = false, description = "Task type identificator")
	private Instant startingDate;

I get this error:

[INFO] --- tomcat7-maven-plugin:2.2:run (default-cli) @ MockWS---
[INFO] Running war on http://localhost:9090/MockWS
[INFO] Creating Tomcat server configuration at C:\WorkMockWS\target\tomcat
[INFO] create webapp with contextPath: /MockWS
ene 30, 2017 2:46:16 PM org.apache.coyote.AbstractProtocol init
INFORMACIËN: Initializing ProtocolHandler ["http-bio-9090"]
ene 30, 2017 2:46:16 PM org.apache.catalina.core.StandardService startInternal
INFORMACIËN: Starting service Tomcat
ene 30, 2017 2:46:16 PM org.apache.catalina.core.StandardEngine startInternal
INFORMACIËN: Starting Servlet Engine: Apache Tomcat/7.0.47
ene 30, 2017 2:46:18 PM com.sun.xml.ws.transport.http.servlet.WSServletContextListener parseAdaptersAndCreateDelegate
GRAVE: WSSERVLET11: failed to parse runtime descriptor: java.lang.StringIndexOutOfBoundsException: String index out of range: 1
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
        at java.lang.String.substring(String.java:1963)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.getNameFromGetter(CustomSchemaWrapper.java:200)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.findProperties(CustomSchemaWrapper.java:167)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.processProperties(CustomSchemaWrapper.java:136)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.<init>(CustomSchemaWrapper.java:64)
        at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:67)
        at com.github.reinert.jjschema.v1.PropertyWrapper.<init>(PropertyWrapper.java:125)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.processProperties(CustomSchemaWrapper.java:139)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.<init>(CustomSchemaWrapper.java:64)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.<init>(CustomSchemaWrapper.java:51)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.<init>(CustomSchemaWrapper.java:47)
        at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:71)
        at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:47)
        at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:39)
        at com.github.reinert.jjschema.v1.JsonSchemaV4Factory.createSchema(JsonSchemaV4Factory.java:36)
        at MockWS.testJsonSchemaGenerator.loadPeriodicTaskSchema(JsonSchemaGenerator.java:45)
        at MockWS.WebService.<init>(WebService.java:35)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at com.sun.xml.ws.api.server.InstanceResolver.createNewInstance(InstanceResolver.java:219)
        at com.sun.xml.ws.api.server.InstanceResolver.createDefault(InstanceResolver.java:184)
        at com.sun.xml.ws.server.EndpointFactory.createEndpoint(EndpointFactory.java:127)
        at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:513)
        at com.sun.xml.ws.transport.http.DeploymentDescriptorParser.parseAdapters(DeploymentDescriptorParser.java:257)
        at com.sun.xml.ws.transport.http.DeploymentDescriptorParser.parse(DeploymentDescriptorParser.java:151)
        at com.sun.xml.ws.transport.http.servlet.WSServletContextListener.parseAdaptersAndCreateDelegate(WSServletContextListener.java:131)
        at com.sun.xml.ws.transport.http.servlet.WSServletContainerInitializer.onStartup(WSServletContainerInitializer.java:65)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5423)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

ene 30, 2017 2:46:18 PM org.apache.catalina.core.StandardContext startInternal
GRAVE: Error during ServletContainerInitializer processing
javax.servlet.ServletException: com.sun.xml.ws.transport.http.servlet.WSServletException: WSSERVLET11: failed to parse runtime descriptor: java.lang.StringIndexOutOfBoundsException: String index out of range: 1
        at com.sun.xml.ws.transport.http.servlet.WSServletContainerInitializer.onStartup(WSServletContainerInitializer.java:70)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5423)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.sun.xml.ws.transport.http.servlet.WSServletException: WSSERVLET11: failed to parse runtime descriptor: java.lang.StringIndexOutOfBoundsException: String index out of range: 1
        at com.sun.xml.ws.transport.http.servlet.WSServletContextListener.parseAdaptersAndCreateDelegate(WSServletContextListener.java:141)
        at com.sun.xml.ws.transport.http.servlet.WSServletContainerInitializer.onStartup(WSServletContainerInitializer.java:65)
        ... 8 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 1
        at java.lang.String.substring(String.java:1963)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.getNameFromGetter(CustomSchemaWrapper.java:200)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.findProperties(CustomSchemaWrapper.java:167)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.processProperties(CustomSchemaWrapper.java:136)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.<init>(CustomSchemaWrapper.java:64)
        at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:67)
        at com.github.reinert.jjschema.v1.PropertyWrapper.<init>(PropertyWrapper.java:125)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.processProperties(CustomSchemaWrapper.java:139)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.<init>(CustomSchemaWrapper.java:64)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.<init>(CustomSchemaWrapper.java:51)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.<init>(CustomSchemaWrapper.java:47)
        at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:71)
        at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:47)
        at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:39)
        at com.github.reinert.jjschema.v1.JsonSchemaV4Factory.createSchema(JsonSchemaV4Factory.java:36)
        at MockWS.JsonSchemaGenerator.loadTaskSchema(JsonSchemaGenerator.java:45)
        at MockWS.WebService.<init>(WebService.java:35)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at com.sun.xml.ws.api.server.InstanceResolver.createNewInstance(InstanceResolver.java:219)
        at com.sun.xml.ws.api.server.InstanceResolver.createDefault(InstanceResolver.java:184)
        at com.sun.xml.ws.server.EndpointFactory.createEndpoint(EndpointFactory.java:127)
        at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:513)
        at com.sun.xml.ws.transport.http.DeploymentDescriptorParser.parseAdapters(DeploymentDescriptorParser.java:257)
        at com.sun.xml.ws.transport.http.DeploymentDescriptorParser.parse(DeploymentDescriptorParser.java:151)
        at com.sun.xml.ws.transport.http.servlet.WSServletContextListener.parseAdaptersAndCreateDelegate(WSServletContextListener.java:131)
        ... 9 more

The parsing code is the standar > schemaFactory.createSchema(PeriodicTask.class);
If I use Date or any other, then there is no problem. Any suggestion? Is there a way or example how to use INSTANT?

**Comment by reinert** [comment]
Solved by #63
