### ISSUE TITLE
Error converting Java interface to Json schema

### ISSUE THREAD

**Issue by architm** [reinert/JJSchema#65]
I am getting the following error while converting **java inteface to json schema**

`Exception in thread "main" java.lang.NullPointerException
at java.lang.Class.isAssignableFrom(Native Method)
at com.github.reinert.jjschema.JsonSchemaGenerator.checkAndProcessType(JsonSchemaGenerator.java:106)
at com.github.reinert.jjschema.JsonSchemaGenerator.generateSchema(JsonSchemaGenerator.java:86)
at com.github.reinert.jjschema.JsonSchemaGenerator.mergeWithParent(JsonSchemaGenerator.java:300)
at com.github.reinert.jjschema.JsonSchemaGenerator.processCustomType(JsonSchemaGenerator.java:140)
at com.github.reinert.jjschema.JsonSchemaGenerator.checkAndProcessType(JsonSchemaGenerator.java:120)
at com.github.reinert.jjschema.JsonSchemaGenerator.generateSchema(JsonSchemaGenerator.java:86)
at SchemaGeneratorTest.main(SchemaGeneratorTest.java:25)`

My query is does jjschema library supports interface conversion or not?

**Comment by reinert** [comment]
It does support Interface. The problem is related to your specific interface. If you put it here I could check what is going on.
