### ISSUE TITLE
Support for java.util.Map

### ISSUE THREAD

**Issue by jsalerno** [reinert/JJSchema#66]
A domain class that has a Map fails - apparently because the Map type is not supported (whilst Collection is). Is there a way to achieve Map element processing for schema generation ?

```import java.util.HashMap;
import java.util.Map;

import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class Preferences {
	private Map<String, String> preferences = new HashMap<String, String>();
}```

Stack:
```Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at com.github.reinert.jjschema.v1.PropertyWrapper.firstToLowerCase(PropertyWrapper.java:374)
	at com.github.reinert.jjschema.v1.PropertyWrapper.processPropertyName(PropertyWrapper.java:369)
	at com.github.reinert.jjschema.v1.PropertyWrapper.getName(PropertyWrapper.java:147)
	at com.github.reinert.jjschema.v1.PropertyWrapper.<init>(PropertyWrapper.java:82)
	at com.github.reinert.jjschema.v1.CustomSchemaWrapper.processProperties(CustomSchemaWrapper.java:151)
	at com.github.reinert.jjschema.v1.CustomSchemaWrapper.<init>(CustomSchemaWrapper.java:76)
	at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:67)
	at com.github.reinert.jjschema.v1.PropertyWrapper.<init>(PropertyWrapper.java:126)
	at com.github.reinert.jjschema.v1.CustomSchemaWrapper.processProperties(CustomSchemaWrapper.java:151)
	at com.github.reinert.jjschema.v1.CustomSchemaWrapper.<init>(CustomSchemaWrapper.java:76)
	at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:67)
	at com.github.reinert.jjschema.v1.PropertyWrapper.<init>(PropertyWrapper.java:126)
	at com.github.reinert.jjschema.v1.CustomSchemaWrapper.processProperties(CustomSchemaWrapper.java:151)
	at com.github.reinert.jjschema.v1.CustomSchemaWrapper.<init>(CustomSchemaWrapper.java:76)
	at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:67)
	at com.github.reinert.jjschema.v1.PropertyWrapper.<init>(PropertyWrapper.java:126)
	at com.github.reinert.jjschema.v1.CustomSchemaWrapper.processProperties(CustomSchemaWrapper.java:151)
	at com.github.reinert.jjschema.v1.CustomSchemaWrapper.<init>(CustomSchemaWrapper.java:76)
	at com.github.reinert.jjschema.v1.CustomSchemaWrapper.<init>(CustomSchemaWrapper.java:52)
	at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:71)
	at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:47)
	at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:39)
	at com.github.reinert.jjschema.v1.JsonSchemaV4Factory.createSchema(JsonSchemaV4Factory.java:36)
```

**Comment by heat** [comment]
what kind of type a Map could be?

maybe a object, but it ins't clear what it's the name of each attribute in the json object result.
`Map<String, String>` will use the hash code, toString as attribute name ?

**Comment by jsalerno** [comment]
Map<String, String> .... quite logically would be interpreted as key-value pairs, right ?
So, for example:

preferences.put("color", "green");
preferences.put("sex", "male");

would result in 
"map" : {
    "color" : "green",
    "sex" : "male"
}

**Comment by heat** [comment]
It's wrong if we check the implementation:
```
public V put(K key, V value) {
    if (key == null)
        return putForNullKey(value);
    int hash = hash(key.hashCode());
```

Even a String use the `hashCode` as key value.
What we see is toString value of the object key when we print a *Map* .

Maybe if we force a generator of attribute names.

```
     @extractor(ExtractorMapAttribute)
     Map<Object, Object> maps;
     ...

    class ExtractorMapAttribute implements Extractor<T> {
        
       @override
       public String extract(T object) {
            return object.toString();
       }   
    }
```

@reinert is there something like that ?

**Comment by reinert** [comment]
I'm not quite sure how to represent a Map as a JsonSchema. Also, keep in mind that JsonSchema represents pre-defined types, not dynamic ones.

There's an [old thread](https://groups.google.com/d/msg/json-schema/a7aCCuR0Caw/nlBq3uPgFjcJ) in json-schema forum about it, whre fge suggests representing two arrays, one for the keys, and other for the values.

I'm not sure this is the result someone would expect from converting a Map to a JsonSchema.
