### ISSUE TITLE
The use of java.time.OffsetDateTime will cause StackOverflowError

### ISSUE THREAD

**Issue by albihnf** [reinert/JJSchema#95]
Hi,
I get a StackoverflowError when using OffsetDateTime

`@Attributes(required = false, description = "Creation timestamp in ISO-8601 format", format="date-time")
	private OffsetDateTime createdTime;`

Part off stacktrace:
`Caused by: java.lang.StackOverflowError: null
        at sun.reflect.generics.parser.SignatureParser.current(SignatureParser.java:95)
        at sun.reflect.generics.parser.SignatureParser.parseZeroOrMoreThrowsSignatures(SignatureParser.java:633)
        at sun.reflect.generics.parser.SignatureParser.parseMethodTypeSignature(SignatureParser.java:578)
        at sun.reflect.generics.parser.SignatureParser.parseMethodSig(SignatureParser.java:171)
        at sun.reflect.generics.repository.ConstructorRepository.parse(ConstructorRepository.java:55)
        at sun.reflect.generics.repository.ConstructorRepository.parse(ConstructorRepository.java:43)
        at sun.reflect.generics.repository.AbstractRepository.<init>(AbstractRepository.java:74)
        at sun.reflect.generics.repository.GenericDeclRepository.<init>(GenericDeclRepository.java:48)
        at sun.reflect.generics.repository.ConstructorRepository.<init>(ConstructorRepository.java:51)
        at sun.reflect.generics.repository.MethodRepository.<init>(MethodRepository.java:46)
        at sun.reflect.generics.repository.MethodRepository.make(MethodRepository.java:59)
        at java.lang.reflect.Method.getGenericInfo(Method.java:99)
        at java.lang.reflect.Method.getGenericReturnType(Method.java:241)
        at com.github.reinert.jjschema.v1.PropertyWrapper.<init>(PropertyWrapper.java:79)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.processProperties(CustomSchemaWrapper.java:155)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.<init>(CustomSchemaWrapper.java:88)
        at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:68)
        at com.github.reinert.jjschema.v1.PropertyWrapper.createWrapper(PropertyWrapper.java:263)
        at com.github.reinert.jjschema.v1.PropertyWrapper.<init>(PropertyWrapper.java:150)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.processProperties(CustomSchemaWrapper.java:155)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.<init>(CustomSchemaWrapper.java:88)
        at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:68)
        at com.github.reinert.jjschema.v1.ArraySchemaWrapper.<init>(ArraySchemaWrapper.java:45)
        at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createArrayWrapper(SchemaWrapperFactory.java:81)
        at com.github.reinert.jjschema.v1.PropertyWrapper.createArrayWrapper(PropertyWrapper.java:268)
        at com.github.reinert.jjschema.v1.PropertyWrapper.<init>(PropertyWrapper.java:146)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.processProperties(CustomSchemaWrapper.java:155)
        at com.github.reinert.jjschema.v1.CustomSchemaWrapper.<init>(CustomSchemaWrapper.java:88)
        at com.github.reinert.jjschema.v1.SchemaWrapperFactory.createWrapper(SchemaWrapperFactory.java:68)
`

**Comment by reinert** [comment]
Thanks for reporting. I'm publishing a new version with this hotfix.
